server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: 1234
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
    topics:
      dead-letter: dead-letter
