spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zz
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
