spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

#logging:
#  level:
#    ROOT: INFO
#    org.hibernate: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.orm: TRACE
#    org.springframework.transaction: TRACE
#    com.zaxxer.hikari: TRACE
#    com.mysql.cj.jdbc: TRACE