spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
#    open-in-view: true # default is true
    open-in-view: false
    hibernate:
      ddl-auto: none

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: osiv-test-group
    producer:
      bootstrap-servers: localhost:9092
    topics:
      osiv-test: osiv-test