server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug